framework:
  messenger:
    transports:
      message: '%env(MESSENGER_TRANSPORT_DSN)%'
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

    routing:
      'App\Dto\Message\MessageInterface': message
